---
- hosts: docker
  become: true
  tasks:
   - name: docker | Install
     package: name=docker.io state=present
   - name: docker | Configure docker
     copy:
       dest: /etc/docker/daemon.json
       content:
        debug: false
     notify:
      - restart docker
   - name: docker | Configure startup options for docker
     copy:
       dest: /etc/default/docker
       content: |
         # Here in Debian, this file is sourced by:
         #   - /etc/init.d/docker (sysvinit)
         #   - /etc/init/docker (upstart)
         #   - systemd's docker.service
         
         # Use of this file for configuring your Docker daemon is discouraged.
         
         # The recommended alternative is "/etc/docker/daemon.json", as described in:
         #   https://docs.docker.com/v1.11/engine/reference/commandline/daemon/#daemon-configuration-file
         
         # If that does not suit your needs, try a systemd drop-in file, as described in:
         #   https://docs.docker.com/v1.11/engine/admin/systemd/#custom-docker-daemon-options
         DOCKER_OPTS='-H tcp://0.0.0.0:2375'
     notify:
      - restart docker
   - name: docker | Configure local environment
     become: false
     delegate_to: '{{ item }}'
     lineinfile:
       path: '{{ hostvars[item].env_location }}'
       line: 'export DOCKER_HOST="tcp://0.0.0.0:2375"'
     with_items: '{{ groups.docker_controller }}'
  handlers:
   - name: restart docker
     become: true
     systemd: name=docker state=restarted

