---
- hosts: vm
  tasks:
   - name: vm | Configure drop caches every minute
     become: true
     cron:
        name: drop_caches
        cron_file: /etc/crontab
        day: '*'
        hour: '*'
        minute: '*'
        month: '*'
        dow: '*'
        state: present
        disabled: false
        job: 'echo 3 > /proc/sys/vm/drop_caches'
        user: root
   - name: vm | Install basic packages
     become: true
     package:
        name:
         - vim
         - atop
         - tcpdump
        state: present
   - name: vm | check if vsyscall=emulate is in command line
     become: true
     lineinfile:
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet vsyscall=emulate"'
        path: /etc/default/grub
     notify:
        - update grub
  handlers:
     - name: update grub
       become: true
       command: /usr/sbin/update-grub
       notify: reboot vm
     - name: reboot vm
       become: true
       reboot:
         reboot_timeout: 70
